// https://www.iso.org/iso-4217-currency-codes.html
// Keys are lowercase ISO 3166-1 alpha-2 country codes, matching the output of `getCountryCode`.
export const currencies: Record<
	string,
	{
		location: string;
		currency: string;
		alphabeticCode?: string;
		numericCode?: string;
		minorUnit?: string;
	}
> = {
	ad: {
		location: "ANDORRA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	ae: {
		location: "UNITED ARAB EMIRATES (THE)",
		currency: "UAE Dirham",
		alphabeticCode: "AED",
		numericCode: "784",
		minorUnit: "2",
	},
	af: {
		location: "AFGHANISTAN",
		currency: "Afghani",
		alphabeticCode: "AFN",
		numericCode: "971",
		minorUnit: "2",
	},
	ag: {
		location: "ANTIGUA AND BARBUDA",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	ai: {
		location: "ANGUILLA",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	al: {
		location: "ALBANIA",
		currency: "Lek",
		alphabeticCode: "ALL",
		numericCode: "008",
		minorUnit: "2",
	},
	am: {
		location: "ARMENIA",
		currency: "Armenian Dram",
		alphabeticCode: "AMD",
		numericCode: "051",
		minorUnit: "2",
	},
	ao: {
		location: "ANGOLA",
		currency: "Kwanza",
		alphabeticCode: "AOA",
		numericCode: "973",
		minorUnit: "2",
	},
	aq: {
		location: "ANTARCTICA",
		currency: "No universal currency",
	},
	ar: {
		location: "ARGENTINA",
		currency: "Argentine Peso",
		alphabeticCode: "ARS",
		numericCode: "032",
		minorUnit: "2",
	},
	as: {
		location: "AMERICAN SAMOA",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	at: {
		location: "AUSTRIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	au: {
		location: "AUSTRALIA",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	aw: {
		location: "ARUBA",
		currency: "Aruban Florin",
		alphabeticCode: "AWG",
		numericCode: "533",
		minorUnit: "2",
	},
	ax: {
		location: "ÅLAND ISLANDS",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	az: {
		location: "AZERBAIJAN",
		currency: "Azerbaijan Manat",
		alphabeticCode: "AZN",
		numericCode: "944",
		minorUnit: "2",
	},
	ba: {
		location: "BOSNIA AND HERZEGOVINA",
		currency: "Convertible Mark",
		alphabeticCode: "BAM",
		numericCode: "977",
		minorUnit: "2",
	},
	bb: {
		location: "BARBADOS",
		currency: "Barbados Dollar",
		alphabeticCode: "BBD",
		numericCode: "052",
		minorUnit: "2",
	},
	bd: {
		location: "BANGLADESH",
		currency: "Taka",
		alphabeticCode: "BDT",
		numericCode: "050",
		minorUnit: "2",
	},
	be: {
		location: "BELGIUM",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	bf: {
		location: "BURKINA FASO",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	bg: {
		location: "BULGARIA",
		currency: "Bulgarian Lev",
		alphabeticCode: "BGN",
		numericCode: "975",
		minorUnit: "2",
	},
	bh: {
		location: "BAHRAIN",
		currency: "Bahraini Dinar",
		alphabeticCode: "BHD",
		numericCode: "048",
		minorUnit: "3",
	},
	bi: {
		location: "BURUNDI",
		currency: "Burundi Franc",
		alphabeticCode: "BIF",
		numericCode: "108",
		minorUnit: "0",
	},
	bj: {
		location: "BENIN",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	bl: {
		location: "SAINT BARTHÉLEMY",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	bm: {
		location: "BERMUDA",
		currency: "Bermudian Dollar",
		alphabeticCode: "BMD",
		numericCode: "060",
		minorUnit: "2",
	},
	bn: {
		location: "BRUNEI DARUSSALAM",
		currency: "Brunei Dollar",
		alphabeticCode: "BND",
		numericCode: "096",
		minorUnit: "2",
	},
	bo: {
		location: "BOLIVIA (PLURINATIONAL STATE OF)",
		currency: "Boliviano",
		alphabeticCode: "BOB",
		numericCode: "068",
		minorUnit: "2",
	},
	bq: {
		location: "BONAIRE, SINT EUSTATIUS AND SABA",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	br: {
		location: "BRAZIL",
		currency: "Brazilian Real",
		alphabeticCode: "BRL",
		numericCode: "986",
		minorUnit: "2",
	},
	bs: {
		location: "BAHAMAS (THE)",
		currency: "Bahamian Dollar",
		alphabeticCode: "BSD",
		numericCode: "044",
		minorUnit: "2",
	},
	bt: {
		location: "BHUTAN",
		currency: "Ngultrum",
		alphabeticCode: "BTN",
		numericCode: "064",
		minorUnit: "2",
	},
	bv: {
		location: "BOUVET ISLAND",
		currency: "Norwegian Krone",
		alphabeticCode: "NOK",
		numericCode: "578",
		minorUnit: "2",
	},
	bw: {
		location: "BOTSWANA",
		currency: "Pula",
		alphabeticCode: "BWP",
		numericCode: "072",
		minorUnit: "2",
	},
	by: {
		location: "BELARUS",
		currency: "Belarusian Ruble",
		alphabeticCode: "BYN",
		numericCode: "933",
		minorUnit: "2",
	},
	bz: {
		location: "BELIZE",
		currency: "Belize Dollar",
		alphabeticCode: "BZD",
		numericCode: "084",
		minorUnit: "2",
	},
	ca: {
		location: "CANADA",
		currency: "Canadian Dollar",
		alphabeticCode: "CAD",
		numericCode: "124",
		minorUnit: "2",
	},
	cc: {
		location: "COCOS (KEELING) ISLANDS (THE)",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	cd: {
		location: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
		currency: "Congolese Franc",
		alphabeticCode: "CDF",
		numericCode: "976",
		minorUnit: "2",
	},
	cf: {
		location: "CENTRAL AFRICAN REPUBLIC (THE)",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	cg: {
		location: "CONGO (THE)",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	ch: {
		location: "SWITZERLAND",
		currency: "Swiss Franc",
		alphabeticCode: "CHF",
		numericCode: "756",
		minorUnit: "2",
	},
	ci: {
		location: "CÔTE D'IVOIRE",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	ck: {
		location: "COOK ISLANDS (THE)",
		currency: "New Zealand Dollar",
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnit: "2",
	},
	cl: {
		location: "CHILE",
		currency: "Chilean Peso",
		alphabeticCode: "CLP",
		numericCode: "152",
		minorUnit: "0",
	},
	cm: {
		location: "CAMEROON",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	cn: {
		location: "CHINA",
		currency: "Yuan Renminbi",
		alphabeticCode: "CNY",
		numericCode: "156",
		minorUnit: "2",
	},
	co: {
		location: "COLOMBIA",
		currency: "Colombian Peso",
		alphabeticCode: "COP",
		numericCode: "170",
		minorUnit: "2",
	},
	cr: {
		location: "COSTA RICA",
		currency: "Costa Rican Colon",
		alphabeticCode: "CRC",
		numericCode: "188",
		minorUnit: "2",
	},
	cu: {
		location: "CUBA",
		currency: "Cuban Peso",
		alphabeticCode: "CUP",
		numericCode: "192",
		minorUnit: "2",
	},
	cv: {
		location: "CABO VERDE",
		currency: "Cabo Verde Escudo",
		alphabeticCode: "CVE",
		numericCode: "132",
		minorUnit: "2",
	},
	cw: {
		location: "CURAÇAO",
		currency: "Netherlands Antillean Guilder",
		alphabeticCode: "ANG",
		numericCode: "532",
		minorUnit: "2",
	},
	cx: {
		location: "CHRISTMAS ISLAND",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	cy: {
		location: "CYPRUS",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	cz: {
		location: "CZECHIA",
		currency: "Czech Koruna",
		alphabeticCode: "CZK",
		numericCode: "203",
		minorUnit: "2",
	},
	de: {
		location: "GERMANY",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	dj: {
		location: "DJIBOUTI",
		currency: "Djibouti Franc",
		alphabeticCode: "DJF",
		numericCode: "262",
		minorUnit: "0",
	},
	dk: {
		location: "DENMARK",
		currency: "Danish Krone",
		alphabeticCode: "DKK",
		numericCode: "208",
		minorUnit: "2",
	},
	dm: {
		location: "DOMINICA",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	do: {
		location: "DOMINICAN REPUBLIC (THE)",
		currency: "Dominican Peso",
		alphabeticCode: "DOP",
		numericCode: "214",
		minorUnit: "2",
	},
	dz: {
		location: "ALGERIA",
		currency: "Algerian Dinar",
		alphabeticCode: "DZD",
		numericCode: "012",
		minorUnit: "2",
	},
	ec: {
		location: "ECUADOR",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	ee: {
		location: "ESTONIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	eg: {
		location: "EGYPT",
		currency: "Egyptian Pound",
		alphabeticCode: "EGP",
		numericCode: "818",
		minorUnit: "2",
	},
	eh: {
		location: "WESTERN SAHARA",
		currency: "Moroccan Dirham",
		alphabeticCode: "MAD",
		numericCode: "504",
		minorUnit: "2",
	},
	er: {
		location: "ERITREA",
		currency: "Nakfa",
		alphabeticCode: "ERN",
		numericCode: "232",
		minorUnit: "2",
	},
	es: {
		location: "SPAIN",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	et: {
		location: "ETHIOPIA",
		currency: "Ethiopian Birr",
		alphabeticCode: "ETB",
		numericCode: "230",
		minorUnit: "2",
	},
	fi: {
		location: "FINLAND",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	fj: {
		location: "FIJI",
		currency: "Fiji Dollar",
		alphabeticCode: "FJD",
		numericCode: "242",
		minorUnit: "2",
	},
	fk: {
		location: "FALKLAND ISLANDS (THE) [MALVINAS]",
		currency: "Falkland Islands Pound",
		alphabeticCode: "FKP",
		numericCode: "238",
		minorUnit: "2",
	},
	fm: {
		location: "MICRONESIA (FEDERATED STATES OF)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	fo: {
		location: "FAROE ISLANDS (THE)",
		currency: "Danish Krone",
		alphabeticCode: "DKK",
		numericCode: "208",
		minorUnit: "2",
	},
	fr: {
		location: "FRANCE",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	ga: {
		location: "GABON",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	gb: {
		location: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
		currency: "Pound Sterling",
		alphabeticCode: "GBP",
		numericCode: "826",
		minorUnit: "2",
	},
	gd: {
		location: "GRENADA",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	ge: {
		location: "GEORGIA",
		currency: "Lari",
		alphabeticCode: "GEL",
		numericCode: "981",
		minorUnit: "2",
	},
	gf: {
		location: "FRENCH GUIANA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	gg: {
		location: "GUERNSEY",
		currency: "Pound Sterling",
		alphabeticCode: "GBP",
		numericCode: "826",
		minorUnit: "2",
	},
	gh: {
		location: "GHANA",
		currency: "Ghana Cedi",
		alphabeticCode: "GHS",
		numericCode: "936",
		minorUnit: "2",
	},
	gi: {
		location: "GIBRALTAR",
		currency: "Gibraltar Pound",
		alphabeticCode: "GIP",
		numericCode: "292",
		minorUnit: "2",
	},
	gl: {
		location: "GREENLAND",
		currency: "Danish Krone",
		alphabeticCode: "DKK",
		numericCode: "208",
		minorUnit: "2",
	},
	gm: {
		location: "GAMBIA (THE)",
		currency: "Dalasi",
		alphabeticCode: "GMD",
		numericCode: "270",
		minorUnit: "2",
	},
	gn: {
		location: "GUINEA",
		currency: "Guinean Franc",
		alphabeticCode: "GNF",
		numericCode: "324",
		minorUnit: "0",
	},
	gp: {
		location: "GUADELOUPE",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	gq: {
		location: "EQUATORIAL GUINEA",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	gr: {
		location: "GREECE",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	gs: {
		location: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
		currency: "No universal currency",
	},
	gt: {
		location: "GUATEMALA",
		currency: "Quetzal",
		alphabeticCode: "GTQ",
		numericCode: "320",
		minorUnit: "2",
	},
	gu: {
		location: "GUAM",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	gw: {
		location: "GUINEA-BISSAU",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	gy: {
		location: "GUYANA",
		currency: "Guyana Dollar",
		alphabeticCode: "GYD",
		numericCode: "328",
		minorUnit: "2",
	},
	hk: {
		location: "HONG KONG",
		currency: "Hong Kong Dollar",
		alphabeticCode: "HKD",
		numericCode: "344",
		minorUnit: "2",
	},
	hm: {
		location: "HEARD ISLAND AND McDONALD ISLANDS",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	hn: {
		location: "HONDURAS",
		currency: "Lempira",
		alphabeticCode: "HNL",
		numericCode: "340",
		minorUnit: "2",
	},
	hr: {
		location: "CROATIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	ht: {
		location: "HAITI",
		currency: "Gourde",
		alphabeticCode: "HTG",
		numericCode: "332",
		minorUnit: "2",
	},
	hu: {
		location: "HUNGARY",
		currency: "Forint",
		alphabeticCode: "HUF",
		numericCode: "348",
		minorUnit: "2",
	},
	id: {
		location: "INDONESIA",
		currency: "Rupiah",
		alphabeticCode: "IDR",
		numericCode: "360",
		minorUnit: "2",
	},
	ie: {
		location: "IRELAND",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	il: {
		location: "ISRAEL",
		currency: "New Israeli Sheqel",
		alphabeticCode: "ILS",
		numericCode: "376",
		minorUnit: "2",
	},
	im: {
		location: "ISLE OF MAN",
		currency: "Pound Sterling",
		alphabeticCode: "GBP",
		numericCode: "826",
		minorUnit: "2",
	},
	in: {
		location: "INDIA",
		currency: "Indian Rupee",
		alphabeticCode: "INR",
		numericCode: "356",
		minorUnit: "2",
	},
	io: {
		location: "BRITISH INDIAN OCEAN TERRITORY (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	iq: {
		location: "IRAQ",
		currency: "Iraqi Dinar",
		alphabeticCode: "IQD",
		numericCode: "368",
		minorUnit: "3",
	},
	ir: {
		location: "IRAN (ISLAMIC REPUBLIC OF)",
		currency: "Iranian Rial",
		alphabeticCode: "IRR",
		numericCode: "364",
		minorUnit: "2",
	},
	is: {
		location: "ICELAND",
		currency: "Iceland Krona",
		alphabeticCode: "ISK",
		numericCode: "352",
		minorUnit: "0",
	},
	it: {
		location: "ITALY",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	je: {
		location: "JERSEY",
		currency: "Pound Sterling",
		alphabeticCode: "GBP",
		numericCode: "826",
		minorUnit: "2",
	},
	jm: {
		location: "JAMAICA",
		currency: "Jamaican Dollar",
		alphabeticCode: "JMD",
		numericCode: "388",
		minorUnit: "2",
	},
	jo: {
		location: "JORDAN",
		currency: "Jordanian Dinar",
		alphabeticCode: "JOD",
		numericCode: "400",
		minorUnit: "3",
	},
	jp: {
		location: "JAPAN",
		currency: "Yen",
		alphabeticCode: "JPY",
		numericCode: "392",
		minorUnit: "0",
	},
	ke: {
		location: "KENYA",
		currency: "Kenyan Shilling",
		alphabeticCode: "KES",
		numericCode: "404",
		minorUnit: "2",
	},
	kg: {
		location: "KYRGYZSTAN",
		currency: "Som",
		alphabeticCode: "KGS",
		numericCode: "417",
		minorUnit: "2",
	},
	kh: {
		location: "CAMBODIA",
		currency: "Riel",
		alphabeticCode: "KHR",
		numericCode: "116",
		minorUnit: "2",
	},
	ki: {
		location: "KIRIBATI",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	km: {
		location: "COMOROS (THE)",
		currency: "Comorian Franc",
		alphabeticCode: "KMF",
		numericCode: "174",
		minorUnit: "0",
	},
	kn: {
		location: "SAINT KITTS AND NEVIS",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	kp: {
		location: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)",
		currency: "North Korean Won",
		alphabeticCode: "KPW",
		numericCode: "408",
		minorUnit: "2",
	},
	kr: {
		location: "KOREA (THE REPUBLIC OF)",
		currency: "Won",
		alphabeticCode: "KRW",
		numericCode: "410",
		minorUnit: "0",
	},
	kw: {
		location: "KUWAIT",
		currency: "Kuwaiti Dinar",
		alphabeticCode: "KWD",
		numericCode: "414",
		minorUnit: "3",
	},
	ky: {
		location: "CAYMAN ISLANDS (THE)",
		currency: "Cayman Islands Dollar",
		alphabeticCode: "KYD",
		numericCode: "136",
		minorUnit: "2",
	},
	kz: {
		location: "KAZAKHSTAN",
		currency: "Tenge",
		alphabeticCode: "KZT",
		numericCode: "398",
		minorUnit: "2",
	},
	la: {
		location: "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)",
		currency: "Lao Kip",
		alphabeticCode: "LAK",
		numericCode: "418",
		minorUnit: "2",
	},
	lb: {
		location: "LEBANON",
		currency: "Lebanese Pound",
		alphabeticCode: "LBP",
		numericCode: "422",
		minorUnit: "2",
	},
	lc: {
		location: "SAINT LUCIA",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	li: {
		location: "LIECHTENSTEIN",
		currency: "Swiss Franc",
		alphabeticCode: "CHF",
		numericCode: "756",
		minorUnit: "2",
	},
	lk: {
		location: "SRI LANKA",
		currency: "Sri Lanka Rupee",
		alphabeticCode: "LKR",
		numericCode: "144",
		minorUnit: "2",
	},
	lr: {
		location: "LIBERIA",
		currency: "Liberian Dollar",
		alphabeticCode: "LRD",
		numericCode: "430",
		minorUnit: "2",
	},
	ls: {
		location: "LESOTHO",
		currency: "Loti",
		alphabeticCode: "LSL",
		numericCode: "426",
		minorUnit: "2",
	},
	lt: {
		location: "LITHUANIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	lu: {
		location: "LUXEMBOURG",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	lv: {
		location: "LATVIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	ly: {
		location: "LIBYA",
		currency: "Libyan Dinar",
		alphabeticCode: "LYD",
		numericCode: "434",
		minorUnit: "3",
	},
	ma: {
		location: "MOROCCO",
		currency: "Moroccan Dirham",
		alphabeticCode: "MAD",
		numericCode: "504",
		minorUnit: "2",
	},
	mc: {
		location: "MONACO",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	md: {
		location: "MOLDOVA (THE REPUBLIC OF)",
		currency: "Moldovan Leu",
		alphabeticCode: "MDL",
		numericCode: "498",
		minorUnit: "2",
	},
	me: {
		location: "MONTENEGRO",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	mf: {
		location: "SAINT MARTIN (FRENCH PART)",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	mg: {
		location: "MADAGASCAR",
		currency: "Malagasy Ariary",
		alphabeticCode: "MGA",
		numericCode: "969",
		minorUnit: "2",
	},
	mh: {
		location: "MARSHALL ISLANDS (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	mk: {
		location: "NORTH MACEDONIA",
		currency: "Denar",
		alphabeticCode: "MKD",
		numericCode: "807",
		minorUnit: "2",
	},
	ml: {
		location: "MALI",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	mm: {
		location: "MYANMAR",
		currency: "Kyat",
		alphabeticCode: "MMK",
		numericCode: "104",
		minorUnit: "2",
	},
	mn: {
		location: "MONGOLIA",
		currency: "Tugrik",
		alphabeticCode: "MNT",
		numericCode: "496",
		minorUnit: "2",
	},
	mo: {
		location: "MACAO",
		currency: "Pataca",
		alphabeticCode: "MOP",
		numericCode: "446",
		minorUnit: "2",
	},
	mp: {
		location: "NORTHERN MARIANA ISLANDS (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	mq: {
		location: "MARTINIQUE",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	mr: {
		location: "MAURITANIA",
		currency: "Ouguiya",
		alphabeticCode: "MRU",
		numericCode: "929",
		minorUnit: "2",
	},
	ms: {
		location: "MONTSERRAT",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	mt: {
		location: "MALTA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	mu: {
		location: "MAURITIUS",
		currency: "Mauritius Rupee",
		alphabeticCode: "MUR",
		numericCode: "480",
		minorUnit: "2",
	},
	mv: {
		location: "MALDIVES",
		currency: "Rufiyaa",
		alphabeticCode: "MVR",
		numericCode: "462",
		minorUnit: "2",
	},
	mw: {
		location: "MALAWI",
		currency: "Malawi Kwacha",
		alphabeticCode: "MWK",
		numericCode: "454",
		minorUnit: "2",
	},
	mx: {
		location: "MEXICO",
		currency: "Mexican Peso",
		alphabeticCode: "MXN",
		numericCode: "484",
		minorUnit: "2",
	},
	my: {
		location: "MALAYSIA",
		currency: "Malaysian Ringgit",
		alphabeticCode: "MYR",
		numericCode: "458",
		minorUnit: "2",
	},
	mz: {
		location: "MOZAMBIQUE",
		currency: "Mozambique Metical",
		alphabeticCode: "MZN",
		numericCode: "943",
		minorUnit: "2",
	},
	na: {
		location: "NAMIBIA",
		currency: "Namibia Dollar",
		alphabeticCode: "NAD",
		numericCode: "516",
		minorUnit: "2",
	},
	nc: {
		location: "NEW CALEDONIA",
		currency: "CFP Franc",
		alphabeticCode: "XPF",
		numericCode: "953",
		minorUnit: "0",
	},
	ne: {
		location: "NIGER (THE)",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	nf: {
		location: "NORFOLK ISLAND",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	ng: {
		location: "NIGERIA",
		currency: "Naira",
		alphabeticCode: "NGN",
		numericCode: "566",
		minorUnit: "2",
	},
	ni: {
		location: "NICARAGUA",
		currency: "Cordoba Oro",
		alphabeticCode: "NIO",
		numericCode: "558",
		minorUnit: "2",
	},
	nl: {
		location: "NETHERLANDS (THE)",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	no: {
		location: "NORWAY",
		currency: "Norwegian Krone",
		alphabeticCode: "NOK",
		numericCode: "578",
		minorUnit: "2",
	},
	np: {
		location: "NEPAL",
		currency: "Nepalese Rupee",
		alphabeticCode: "NPR",
		numericCode: "524",
		minorUnit: "2",
	},
	nr: {
		location: "NAURU",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	nu: {
		location: "NIUE",
		currency: "New Zealand Dollar",
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnit: "2",
	},
	nz: {
		location: "NEW ZEALAND",
		currency: "New Zealand Dollar",
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnit: "2",
	},
	om: {
		location: "OMAN",
		currency: "Rial Omani",
		alphabeticCode: "OMR",
		numericCode: "512",
		minorUnit: "3",
	},
	pa: {
		location: "PANAMA",
		currency: "Balboa",
		alphabeticCode: "PAB",
		numericCode: "590",
		minorUnit: "2",
	},
	pe: {
		location: "PERU",
		currency: "Sol",
		alphabeticCode: "PEN",
		numericCode: "604",
		minorUnit: "2",
	},
	pf: {
		location: "FRENCH POLYNESIA",
		currency: "CFP Franc",
		alphabeticCode: "XPF",
		numericCode: "953",
		minorUnit: "0",
	},
	pg: {
		location: "PAPUA NEW GUINEA",
		currency: "Kina",
		alphabeticCode: "PGK",
		numericCode: "598",
		minorUnit: "2",
	},
	ph: {
		location: "PHILIPPINES (THE)",
		currency: "Philippine Peso",
		alphabeticCode: "PHP",
		numericCode: "608",
		minorUnit: "2",
	},
	pk: {
		location: "PAKISTAN",
		currency: "Pakistan Rupee",
		alphabeticCode: "PKR",
		numericCode: "586",
		minorUnit: "2",
	},
	pl: {
		location: "POLAND",
		currency: "Zloty",
		alphabeticCode: "PLN",
		numericCode: "985",
		minorUnit: "2",
	},
	pm: {
		location: "SAINT PIERRE AND MIQUELON",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	pn: {
		location: "PITCAIRN",
		currency: "New Zealand Dollar",
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnit: "2",
	},
	pr: {
		location: "PUERTO RICO",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	ps: {
		location: "PALESTINE, STATE OF",
		currency: "No universal currency",
	},
	pt: {
		location: "PORTUGAL",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	pw: {
		location: "PALAU",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	py: {
		location: "PARAGUAY",
		currency: "Guarani",
		alphabeticCode: "PYG",
		numericCode: "600",
		minorUnit: "0",
	},
	qa: {
		location: "QATAR",
		currency: "Qatari Rial",
		alphabeticCode: "QAR",
		numericCode: "634",
		minorUnit: "2",
	},
	re: {
		location: "RÉUNION",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	ro: {
		location: "ROMANIA",
		currency: "Romanian Leu",
		alphabeticCode: "RON",
		numericCode: "946",
		minorUnit: "2",
	},
	rs: {
		location: "SERBIA",
		currency: "Serbian Dinar",
		alphabeticCode: "RSD",
		numericCode: "941",
		minorUnit: "2",
	},
	ru: {
		location: "RUSSIAN FEDERATION (THE)",
		currency: "Russian Ruble",
		alphabeticCode: "RUB",
		numericCode: "643",
		minorUnit: "2",
	},
	rw: {
		location: "RWANDA",
		currency: "Rwanda Franc",
		alphabeticCode: "RWF",
		numericCode: "646",
		minorUnit: "0",
	},
	sa: {
		location: "SAUDI ARABIA",
		currency: "Saudi Riyal",
		alphabeticCode: "SAR",
		numericCode: "682",
		minorUnit: "2",
	},
	sb: {
		location: "SOLOMON ISLANDS",
		currency: "Solomon Islands Dollar",
		alphabeticCode: "SBD",
		numericCode: "090",
		minorUnit: "2",
	},
	sc: {
		location: "SEYCHELLES",
		currency: "Seychelles Rupee",
		alphabeticCode: "SCR",
		numericCode: "690",
		minorUnit: "2",
	},
	sd: {
		location: "SUDAN (THE)",
		currency: "Sudanese Pound",
		alphabeticCode: "SDG",
		numericCode: "938",
		minorUnit: "2",
	},
	se: {
		location: "SWEDEN",
		currency: "Swedish Krona",
		alphabeticCode: "SEK",
		numericCode: "752",
		minorUnit: "2",
	},
	sg: {
		location: "SINGAPORE",
		currency: "Singapore Dollar",
		alphabeticCode: "SGD",
		numericCode: "702",
		minorUnit: "2",
	},
	sh: {
		location: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
		currency: "Saint Helena Pound",
		alphabeticCode: "SHP",
		numericCode: "654",
		minorUnit: "2",
	},
	si: {
		location: "SLOVENIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	sj: {
		location: "SVALBARD AND JAN MAYEN",
		currency: "Norwegian Krone",
		alphabeticCode: "NOK",
		numericCode: "578",
		minorUnit: "2",
	},
	sk: {
		location: "SLOVAKIA",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	sl: {
		location: "SIERRA LEONE",
		currency: "Leone",
		alphabeticCode: "SLE",
		numericCode: "925",
		minorUnit: "2",
	},
	sm: {
		location: "SAN MARINO",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	sn: {
		location: "SENEGAL",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	so: {
		location: "SOMALIA",
		currency: "Somali Shilling",
		alphabeticCode: "SOS",
		numericCode: "706",
		minorUnit: "2",
	},
	sr: {
		location: "SURINAME",
		currency: "Surinam Dollar",
		alphabeticCode: "SRD",
		numericCode: "968",
		minorUnit: "2",
	},
	ss: {
		location: "SOUTH SUDAN",
		currency: "South Sudanese Pound",
		alphabeticCode: "SSP",
		numericCode: "728",
		minorUnit: "2",
	},
	st: {
		location: "SAO TOME AND PRINCIPE",
		currency: "Dobra",
		alphabeticCode: "STN",
		numericCode: "930",
		minorUnit: "2",
	},
	sv: {
		location: "EL SALVADOR",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	sx: {
		location: "SINT MAARTEN (DUTCH PART)",
		currency: "Netherlands Antillean Guilder",
		alphabeticCode: "ANG",
		numericCode: "532",
		minorUnit: "2",
	},
	sy: {
		location: "SYRIAN ARAB REPUBLIC",
		currency: "Syrian Pound",
		alphabeticCode: "SYP",
		numericCode: "760",
		minorUnit: "2",
	},
	sz: {
		location: "ESWATINI",
		currency: "Lilangeni",
		alphabeticCode: "SZL",
		numericCode: "748",
		minorUnit: "2",
	},
	tc: {
		location: "TURKS AND CAICOS ISLANDS (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	td: {
		location: "CHAD",
		currency: "CFA Franc BEAC",
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnit: "0",
	},
	tf: {
		location: "FRENCH SOUTHERN TERRITORIES (THE)",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	tg: {
		location: "TOGO",
		currency: "CFA Franc BCEAO",
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnit: "0",
	},
	th: {
		location: "THAILAND",
		currency: "Baht",
		alphabeticCode: "THB",
		numericCode: "764",
		minorUnit: "2",
	},
	tj: {
		location: "TAJIKISTAN",
		currency: "Somoni",
		alphabeticCode: "TJS",
		numericCode: "972",
		minorUnit: "2",
	},
	tk: {
		location: "TOKELAU",
		currency: "New Zealand Dollar",
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnit: "2",
	},
	tl: {
		location: "TIMOR-LESTE",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	tm: {
		location: "TURKMENISTAN",
		currency: "Turkmenistan New Manat",
		alphabeticCode: "TMT",
		numericCode: "934",
		minorUnit: "2",
	},
	tn: {
		location: "TUNISIA",
		currency: "Tunisian Dinar",
		alphabeticCode: "TND",
		numericCode: "788",
		minorUnit: "3",
	},
	to: {
		location: "TONGA",
		currency: "Pa’anga",
		alphabeticCode: "TOP",
		numericCode: "776",
		minorUnit: "2",
	},
	tr: {
		location: "TURKEY",
		currency: "Turkish Lira",
		alphabeticCode: "TRY",
		numericCode: "949",
		minorUnit: "2",
	},
	tt: {
		location: "TRINIDAD AND TOBAGO",
		currency: "Trinidad and Tobago Dollar",
		alphabeticCode: "TTD",
		numericCode: "780",
		minorUnit: "2",
	},
	tv: {
		location: "TUVALU",
		currency: "Australian Dollar",
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnit: "2",
	},
	tw: {
		location: "TAIWAN (PROVINCE OF CHINA)",
		currency: "New Taiwan Dollar",
		alphabeticCode: "TWD",
		numericCode: "901",
		minorUnit: "2",
	},
	tz: {
		location: "TANZANIA, UNITED REPUBLIC OF",
		currency: "Tanzanian Shilling",
		alphabeticCode: "TZS",
		numericCode: "834",
		minorUnit: "2",
	},
	ua: {
		location: "UKRAINE",
		currency: "Hryvnia",
		alphabeticCode: "UAH",
		numericCode: "980",
		minorUnit: "2",
	},
	ug: {
		location: "UGANDA",
		currency: "Uganda Shilling",
		alphabeticCode: "UGX",
		numericCode: "800",
		minorUnit: "0",
	},
	um: {
		location: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	us: {
		location: "UNITED STATES OF AMERICA (THE)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	uy: {
		location: "URUGUAY",
		currency: "Peso Uruguayo",
		alphabeticCode: "UYU",
		numericCode: "858",
		minorUnit: "2",
	},
	uz: {
		location: "UZBEKISTAN",
		currency: "Uzbekistan Sum",
		alphabeticCode: "UZS",
		numericCode: "860",
		minorUnit: "2",
	},
	va: {
		location: "HOLY SEE (THE)",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	vc: {
		location: "SAINT VINCENT AND THE GRENADINES",
		currency: "East Caribbean Dollar",
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnit: "2",
	},
	ve: {
		location: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
		currency: "Bolívar Soberano",
		alphabeticCode: "VES",
		numericCode: "928",
		minorUnit: "2",
	},
	vg: {
		location: "VIRGIN ISLANDS (BRITISH)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	vi: {
		location: "VIRGIN ISLANDS (U.S.)",
		currency: "US Dollar",
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnit: "2",
	},
	vn: {
		location: "VIET NAM",
		currency: "Dong",
		alphabeticCode: "VND",
		numericCode: "704",
		minorUnit: "0",
	},
	vu: {
		location: "VANUATU",
		currency: "Vatu",
		alphabeticCode: "VUV",
		numericCode: "548",
		minorUnit: "0",
	},
	wf: {
		location: "WALLIS AND FUTUNA",
		currency: "CFP Franc",
		alphabeticCode: "XPF",
		numericCode: "953",
		minorUnit: "0",
	},
	ws: {
		location: "SAMOA",
		currency: "Tala",
		alphabeticCode: "WST",
		numericCode: "882",
		minorUnit: "2",
	},
	ye: {
		location: "YEMEN",
		currency: "Yemeni Rial",
		alphabeticCode: "YER",
		numericCode: "886",
		minorUnit: "2",
	},
	yt: {
		location: "MAYOTTE",
		currency: "Euro",
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnit: "2",
	},
	za: {
		location: "SOUTH AFRICA",
		currency: "Rand",
		alphabeticCode: "ZAR",
		numericCode: "710",
		minorUnit: "2",
	},
	zm: {
		location: "ZAMBIA",
		currency: "Zambian Kwacha",
		alphabeticCode: "ZMW",
		numericCode: "967",
		minorUnit: "2",
	},
	zw: {
		location: "ZIMBABWE",
		currency: "Zimbabwe Gold",
		alphabeticCode: "ZWG",
		numericCode: "924",
		minorUnit: "2",
	},
};
